import type { CalendarEvent, Note, Message, Series, Contact } from './types';

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'c1',
    name: 'Margaret Chen',
    relationshipType: 'congregant',
    phone: '555-0101',
    email: 'margaret.chen@email.com',
    notes: '',
    tags: ['deacon', 'senior'],
  },
  {
    id: 'c2',
    name: 'James Davis',
    relationshipType: 'congregant',
    phone: '555-0102',
    email: 'james.davis@email.com',
    notes: '',
    tags: [],
  },
  {
    id: 'c3',
    name: 'Sarah Wong',
    relationshipType: 'congregant',
    phone: '555-0103',
    email: 'sarah.wong@email.com',
    notes: '',
    tags: [],
  },
  {
    id: 'c4',
    name: 'Robert Mills',
    relationshipType: 'congregant',
    phone: '555-0104',
    email: '',
    notes: '',
    tags: ['senior'],
  },
];

export const SEED_SERIES: Series[] = [
  {
    id: 's1',
    title: 'Encounters with Jesus',
    description: 'A summer series on the transformative moments people met Christ in the Gospels.',
    startDate: '2026-07-05',
    endDate: '2026-08-16',
    messageIds: ['m1', 'm2', 'm3', 'm5', 'm6'],
  },
  {
    id: 's2',
    title: 'Summer in the Psalms',
    description: 'Exploring the depths of human experience through the ancient poems of Israel.',
    startDate: '2026-06-07',
    endDate: '2026-07-26',
    messageIds: ['m4'],
  },
];

export const SEED_EVENTS: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Hospital Visit — Margaret Chen',
    type: 'hospital_visit',
    location: 'Memorial Hospital, Room 314',
    startTime: '2026-08-08T14:00:00',
    endTime: '2026-08-08T15:00:00',
    linkedContactId: 'c1',
    notes: 'Post-surgery recovery. Bring communion elements.',
    reminder: '30m',
  },
  {
    id: 'e2',
    title: 'Premarital Counseling — Davis/Wong',
    type: 'counseling',
    location: 'Church Office',
    startTime: '2026-08-08T16:30:00',
    endTime: '2026-08-08T18:00:00',
    notes: 'Session 3 of 6. Focus on communication and conflict.',
    reminder: '1h',
  },
  {
    id: 'e3',
    title: 'Sunday Morning Service',
    type: 'service',
    location: 'First Community Church',
    startTime: '2026-08-09T10:00:00',
    endTime: '2026-08-09T11:30:00',
    recurrence: 'weekly',
    notes: 'Series conclusion: "Who Do You Say I Am?"',
  },
  {
    id: 'e4',
    title: 'Staff Meeting',
    type: 'meeting',
    location: 'Conference Room B',
    startTime: '2026-08-11T09:00:00',
    endTime: '2026-08-11T10:30:00',
    notes: 'Fall programming review and budget discussion.',
  },
  {
    id: 'e5',
    title: 'Funeral Service — Robert Mills',
    type: 'funeral',
    location: 'Riverside Chapel',
    startTime: '2026-08-13T11:00:00',
    endTime: '2026-08-13T13:00:00',
    linkedContactId: 'c4',
    notes: 'Family requested Psalm 23 and "It Is Well." Graveside to follow.',
  },
  {
    id: 'e6',
    title: 'Sunday Morning Service',
    type: 'service',
    location: 'First Community Church',
    startTime: '2026-08-16T10:00:00',
    endTime: '2026-08-16T11:30:00',
    recurrence: 'weekly',
  },
  {
    id: 'e7',
    title: 'Speaking — Youth Retreat Opening Night',
    type: 'speaking',
    location: 'Camp Covenant, Lake Geneva',
    startTime: '2026-08-22T19:00:00',
    endTime: '2026-08-22T20:30:00',
    notes: 'Theme: "Come and See." Audience: high school students.',
  },
  {
    id: 'e8',
    title: 'Wedding Ceremony — Torres/Nakamura',
    type: 'wedding',
    location: 'Hillside Gardens',
    startTime: '2026-08-30T16:00:00',
    endTime: '2026-08-30T18:00:00',
    notes: 'Rehearsal dinner Aug 29. Ceremony script finalized.',
  },
];

export const SEED_MESSAGES: Message[] = [
  {
    id: 'm1',
    title: 'The Prodigal Father',
    dateDelivered: '2026-08-02',
    seriesId: 's1',
    scriptureRefs: ['Luke 15:11-32', '2 Corinthians 5:17'],
    tags: ['grace', 'forgiveness', 'prodigal', 'father'],
    outline: `Introduction: Two sons, one Father — we often miss who this parable is really about.\n\n1. The younger son's departure\n   - Demanding inheritance = wishing the father dead\n   - The far country: what it looks like to live as if God is not\n\n2. The father's posture\n   - He sees from a distance — he was watching, waiting\n   - Runs — undignified, countercultural, scandalous\n   - Robe, ring, sandals, fatted calf — full restoration, not servant status\n\n3. The older son's scandal\n   - Anger at grace extended to the undeserving\n   - "I've never disobeyed" — works-based identity\n   - The father goes out to him too\n\nConclusion: The gospel is not merely that we come home. It is that the Father ran toward us while we were still far off.`,
    status: 'delivered',
  },
  {
    id: 'm2',
    title: 'Fear Not',
    dateDelivered: '2026-07-26',
    seriesId: 's1',
    scriptureRefs: ['Isaiah 41:10', 'Matthew 14:27', 'Revelation 1:17'],
    tags: ['fear', 'courage', 'presence', 'storms'],
    outline: `The three "fear not" passages — each spoken in a different kind of darkness.\n\n1. Isaiah 41:10 — to a people in exile\n   - Not "don't be afraid because things will be fine"\n   - "Do not fear, for I am with you" — the basis is presence, not circumstances\n\n2. Matthew 14:27 — to disciples in a storm\n   - "It is I" — literally "I AM" — divine name in the storm\n   - Jesus doesn't stop the storm first, then speak; he speaks into the storm\n\n3. Revelation 1:17 — to John in apocalyptic vision\n   - "I am the first and the last, and the living one"\n   - Fear meets the resurrected Christ — and is quieted\n\nConclusion: The repeated command "fear not" is God's acknowledgment that we will encounter fear — and his refusal to leave us in it.`,
    status: 'delivered',
  },
  {
    id: 'm3',
    title: 'Living Water',
    dateDelivered: '2026-07-19',
    seriesId: 's1',
    scriptureRefs: ['John 4:1-30', 'Revelation 22:17'],
    tags: ['thirst', 'encounter', 'outcast', 'women'],
    outline: `The woman at the well — a story of unexpected encounter and transformation.\n\n1. The setting of scandal\n   - Noon-day well visit — the margins of the margins\n   - Jesus initiates, asks, and receives\n\n2. The offer of living water\n   - She hears it literally, he means it spiritually\n\n3. "Go call your husband"\n   - He knows. She deflects. He doesn't condemn.\n\n4. She becomes the first missionary\n   - "Come and see a man who told me everything"\n   - The village believes because of her testimony\n\nConclusion: Jesus crosses every barrier to find the one who is thirsty.`,
    status: 'delivered',
  },
  {
    id: 'm4',
    title: 'The Good Shepherd',
    dateDelivered: '2026-07-12',
    seriesId: 's2',
    scriptureRefs: ['Psalm 23', 'John 10:11-18'],
    tags: ['shepherd', 'care', 'provision', 'Psalms'],
    outline: `Psalm 23 and John 10 in conversation — the Shepherd who lays down his life.\n\n1. The Lord is my Shepherd — Psalm 23:1\n   - Not "a shepherd" — the shepherd\n   - All the green pastures, still waters, dark valleys follow from this one claim\n\n2. I know my own — John 10:14\n   - The shepherd knows each sheep by name\n\n3. The Good Shepherd lays down his life\n   - Not taken from him — he lays it down of his own accord\n   - The shepherd becomes the sacrificial lamb\n\nConclusion: Psalm 23 is a promise. John 10 is the explanation of how it is kept.`,
    status: 'delivered',
  },
  {
    id: 'm5',
    title: 'Who Do You Say I Am?',
    dateDelivered: '2026-07-05',
    seriesId: 's1',
    scriptureRefs: ['Matthew 16:13-20', 'Mark 8:27-30'],
    tags: ['identity', 'confession', 'Messiah', 'Peter'],
    outline: `The pivot point of the Gospels.\n\n1. Caesarea Philippi: the context of the question\n   - Shrine to Caesar, grotto of Pan — competing claims to lordship\n\n2. "But who do YOU say I am?"\n   - The move from public opinion to personal confession\n\n3. Peter's answer and Christ's affirmation\n   - "You are the Christ, the Son of the Living God"\n   - "Flesh and blood has not revealed this to you"\n\n4. The weight of the confession\n   - Immediately follows: "Take up your cross"\n\nConclusion: The question is still being asked. Our answer shapes everything.`,
    status: 'delivered',
  },
  {
    id: 'm6',
    title: 'Walking on Water',
    dateDelivered: undefined,
    seriesId: 's1',
    scriptureRefs: ['Matthew 14:22-33'],
    tags: ['faith', 'doubt', 'Peter', 'storms', 'miracles'],
    outline: `Draft — Working notes for the series conclusion.\n\n1. The disciples alone in the boat — Jesus has sent them ahead\n   - We often follow Jesus into the storm\n   - Fourth watch of the night — darkest, when hope fades\n\n2. "Take heart; it is I. Do not be afraid."\n   - ego eimi = I AM\n   - The storm hasn't ended — the presence has arrived\n\n3. Peter's request and walk\n   - Remarkable that he asks. More remarkable that Jesus says "Come."\n   - He walked on water. Even in doubt, he got further than the others.\n\n4. "Lord, save me"\n   - The shortest, most honest prayer in Scripture\n\nConclusion: To be drafted — focus on the invitation to step out, even with doubt.`,
    status: 'draft',
  },
];

export const SEED_NOTES: Note[] = [
  {
    id: 'n1',
    title: 'Outline: The Prodigal Father',
    body: "Working through the sermon structure for Sunday, August 2. Key insight: the parable is named wrong — it's not about the prodigal son, but about the extravagant father. Rereading Kenneth Bailey's \"Poet and Peasant\" — his cultural background is invaluable here.\n\nKey question for the congregation: Which son are you? We're all either the one who has run away or the one who has stayed and grown resentful.",
    type: 'sermon_prep',
    scriptureRefs: ['Luke 15:11-32', '2 Corinthians 5:17'],
    linkedMessageId: 'm1',
    isPrivate: false,
    createdAt: '2026-07-28T10:30:00Z',
    updatedAt: '2026-07-31T14:22:00Z',
    tags: ['grace', 'forgiveness', 'parable'],
  },
  {
    id: 'n2',
    title: 'Reflection: On Being Present in Grief',
    body: "Visited Robert Mills today. He knows. His family knows. There isn't much to say — and that's the point. Job's friends did their best work in the first seven days, when they sat silent.\n\nNote to self: resist the urge to fill silence with theology. Presence is the ministry right now.",
    type: 'personal',
    scriptureRefs: ['Job 2:13', 'Romans 12:15'],
    isPrivate: false,
    createdAt: '2026-08-01T17:45:00Z',
    updatedAt: '2026-08-01T17:45:00Z',
    tags: ['grief', 'presence', 'pastoral care'],
  },
  {
    id: 'n3',
    title: 'Davis/Wong — Session 3 Notes',
    body: 'Session 3 of 6. Focus on communication patterns and conflict resolution.\n\nProgress: Both are engaging honestly. James tends to withdraw; Sarah pushes for resolution too quickly. Introduced the "pause and return" technique.\n\nHomework: Daily 15-minute check-in conversations before next session.\n\nConcerns: Financial stress is an undercurrent — not addressed directly yet. Will introduce in Session 4.',
    type: 'counseling',
    scriptureRefs: ['Ephesians 4:26-27', 'Proverbs 15:1'],
    linkedContactId: 'c2',
    isPrivate: true,
    createdAt: '2026-08-01T18:30:00Z',
    updatedAt: '2026-08-01T18:30:00Z',
    tags: ['premarital', 'communication'],
  },
  {
    id: 'n4',
    title: 'Study: Kingdom Parables — Matthew 13',
    body: "Working through the parables of the kingdom in Matthew 13. What strikes me is the hiddenness — mustard seed, yeast, hidden treasure. The kingdom doesn't announce itself with fanfare; it works quietly, out of sight.\n\nQuestion: Is this a pastoral corrective for people who expect dramatic transformation? Most sanctification is invisible until it isn't.\n\nAlso noting the two 'sell everything' parables — the joy of discovery precedes the cost of discipleship. We get the order backwards when we lead with sacrifice.",
    type: 'study',
    scriptureRefs: ['Matthew 13:1-52', 'Matthew 13:31-33', 'Matthew 13:44-46'],
    isPrivate: false,
    createdAt: '2026-08-05T09:15:00Z',
    updatedAt: '2026-08-07T08:30:00Z',
    tags: ['kingdom', 'parables', 'Matthew', 'discipleship'],
  },
];
